language: go
sudo: false
go:
  - 1.9.2
  - master
env:
  matrix:
    - JOB=test
    - JOB=fmt
addons:
  apt:
    packages:
      - bzr
      - git
      - mercurial
install: make get
script:
  - 'if [ "${JOB}" = "test" ]; then make test; fi'
  - 'if [ "${JOB}" = "fmt" ]; then ./check-fmt.sh; fi'
jobs:
  fast_finish: true
  allow_failures:
    - go: master
